# Generated by Django 5.1.7 on 2025-03-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('echoapp', '0002_alter_book_options_book_image_book_isbn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
    ]
